export const STORY_FLAGS = Object.freeze({
  HAS_ROCK_BREAKER: 'HAS_ROCK_BREAKER',
  RANGER_BRIEFED: 'RANGER_BRIEFED',
  FOREST_SUPPLIES_READY: 'FOREST_SUPPLIES_READY',
  ROCKS_CLEARED: 'ROCKS_CLEARED',
});

export const STORY_ITEM_IDS = Object.freeze({
  ROCK_BREAKER: 3,
});
